### ISSUE TITLE
[beta.30] login with wamp and password crashes the process.

### ISSUE THREAD

**Issue by Jopie01** [Leapsight/bondy#7]
I have beta.30 working but my Python clients which were able to connect to earlier versions cannot connect anymore. This clients are using a username and password combination, but the login crashes with:

```
(bondy@127.0.0.1)1>
when=2022-02-14T09:59:29.015218+00:00 level=info pid=<0.3071.0> at=: description="Established connection with peer" realm=undefined session_id=3Ezrdsy3ggRpC0p1DCzUiN8jYOt peername=127.0.0.1:58564 transport=websocket serializer=msgpack protocol=wamp frame_type=binary agent=undefined 
when=2022-02-14T09:59:29.028526+00:00 level=error pid=<0.3071.0> at=bondy_wamp_protocol:handle_inbound_messages/2:358 reason=badarg state_name=closed stacktrace="[{erlang,iolist_to_binary,[undefined],[{error_info,#{module => erl_erts_errors}}]},{crypto,mac_init,3,[{file,\"crypto.erl\"},{line,702}]},{pbkdf2,'-resolve_mac_func/1-fun-0-',3,[{file,\"/home/bondytest/Erlang/erl_24/bondy/_build/default/lib/pbkdf2/src/pbkdf2.erl\"},{line,140}]},{pbkdf2,pbkdf2,8,[{file,\"/home/bondytest/Erlang/erl_24/bondy/_build/default/lib/pbkdf2/src/pbkdf2.erl\"},{line,125}]},{pbkdf2,pbkdf2,7,[{file,\"/home/bondytest/Erlang/erl_24/bondy/_build/default/lib/pbkdf2/src/pbkdf2.erl\"},{line,104}]},{pbkdf2,pbkdf2,5,[{file,\"/home/bondytest/Erlang/erl_24/bondy/_build/default/lib/pbkdf2/src/pbkdf2.erl\"},{line,61}]},{bondy_password_cra,salted_password,3,[{file,\"/home/bondytest/Erlang/erl_24/bondy/apps/bondy/src/bondy_password_cra.erl\"},{line,183}]},{bondy_password_cra,verify_string,3,[{file,\"/home/bondytest/Erlang/erl_24/bondy/apps/bondy/src/bondy_password_cra.erl\"},{line,88}]}]" class=error 
when=2022-02-14T09:59:29.028855+00:00 level=error pid=<0.3071.0> at=: description="Process crashed" reason=badarg realm=undefined session_id=3Ezrdsy3ggRpC0p1DCzUiN8jYOt peername=127.0.0.1:58564 transport=websocket serializer=msgpack protocol=wamp frame_type=binary class=error agent=undefined 
```

**Comment by aramallo** [comment]
Umm seems like you are not really sending the password (but if that is the case we should be crashing earlier with a proper error). I'll check that later on today. Thanks @Jopie64

**Comment by Jopie01** [comment]
I'm using this piece of code:

```python
PRINCIPAL = "user"
PRINCIPAL_TICKET = "password"

def onConnect(self):
    self.join(self.config.realm, ["password"], PRINCIPAL)

def onChallenge(self, challenge):
    if challenge.method == "password":
        return PRINCIPAL_TICKET
    else:
        raise Exception("Invalid authmethod {}".format(challenge.method))
```
Which works with earlier versions of Bondy. I'm trying to find the version where is stopped working.

**Comment by Jopie01** [comment]
Problem seems to be introduced with beta.26

**Comment by Jopie01** [comment]
I was able to track it down to commit 0377154ffb1d0d77ca04fb35be89b636d2cfe98b which fixes `a ticket authenticate bug`.

So what should I do? The above is also working with crossbar itself and I don't see anything wrong here.

**Comment by aramallo** [comment]
@Jopie01 I found the issue. I will push to develop. We have some more fixes to push and we will create a new tag soon.

BTW, wouldn't you prefer to use WAMPCRA as opposed to password? We will have WAMP SCRAM available very soon too.

**Comment by Jopie01** [comment]
Thank @aramallo for fixing the issue! It works again like a charm.

> BTW, wouldn't you prefer to use WAMPCRA as opposed to password? We will have WAMP SCRAM available very soon too.

I'm working on a test server which is not connected to the internet and I'm developing the different workers around Bondy to get everything working. Then I'm going to look into the different security methods, but parts will be using cryptosign and for others I'm still thinking about it.
